# Generated by Django 3.2.24 on 2024-02-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_fileter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_fileter',
            new_name='image_filter',
        ),
    ]
